### ISSUE TITLE
DMCA Contact

### ISSUE THREAD

**Issue by SW-Ques** [citizenparker/swsheets#106]
Is there a website admin for swsheet.com that can take a DMCA request without having to go through all the verisign private registar hoops to identify them?

**Comment by sparkertime** [comment]
That's basically me. Assuming you mean DMCA, I don't host images on swsheets so I'm curious what content you believe infringes on copyright. Is someone's character an infringement of your copyright?

**Comment by SW-Ques** [comment]
A friend's photo.  He's looking for a contact email.  It's his image that has been used

**Comment by SW-Ques** [comment]
it's used in a character sheet

**Comment by sparkertime** [comment]
If you post the profile, I'll let you know the URL that is hosting the image. There's not much else I can do

**Comment by SW-Ques** [comment]
http://swsheets.com/c/t6hjgynwp-rom-salka?fbclid=IwAR10-x4OoI6ggPMo5Cakh-cr4yGNOnCX3p7wDaD5vj_miljoGnjrclnKZ_w

thanks

**Comment by sparkertime** [comment]
Thanks. That image actually lives at https://i.pinimg.com/564x/d5/2c/c6/d52cc63bf1c28efce03e5b9467ab8d97.jpg so you'll have to contact them about copyright infringement if you want it taken offline. If there's any other characters you see this on, in most browsers you can right-click the image and select "Open in New Tab" if you want to know what website hosts it. I just link to images but I do not host them.

**Comment by SW-Ques** [comment]
Thanks Sparker.   I'm not familiar with git hub. Is there a was to close this or delete it?

**Comment by sparkertime** [comment]
Done!
