### ISSUE TITLE
Potential updates to models

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#113]
I'll put these all in one issue for now, but can break them out into separate ones based upon feedback, or just close this issue entirely if these are not things that should be done or introduce unneeded complexity.

- Add ranks to talents. You can have a rank >1 in a talent if it exists more than once in your talent tree(s).
- Add a quantity for weapons. Ex. carrying >1 frag grenade. 
- Make crit a field with a roll #, difficulty and description instead of a free form field.

**Comment by sparkertime** [comment]
I don't have an objection to the first two. I think the form is cleaner without them, but you've done enough quality work already that you've totally earned the right to call your own shots. So feel free to PR those and I'll accept them.

For crits, there are 615 characters with a non-null value for `critical_injuries`. Those values run the gamut from proper critical injuries to installed cybernetics to whatever people felt like putting in this field. Here are the most recent 9 non-null values as a sample

```
-[ RECORD 1 ]-----+
critical_injuries |  Sightless Vision - Miraluka can perceive their surroundings without needing light or darkness by using the Force.\r
                  | \r
                  | Image Technology Blindness - Cannot read or see screens, datapads, or holos.
-[ RECORD 2 ]-----+
critical_injuries | When performing the assist maneuver, Togrutas grant 2B instead of 1B
-[ RECORD 3 ]-----+
critical_injuries | Mechanics (Cyber Tech) - 1 Rank
-[ RECORD 4 ]-----+
critical_injuries | Scattered Senses = Removes all boosts until effect is removed.
-[ RECORD 5 ]-----+
critical_injuries | Scrapped For Parts
-[ RECORD 6 ]-----+
critical_injuries | Secondary Specialty: Cybernetics\r
                  | \r
                  | \r
                  | Droid crafting:\r
                  | *When crafting VT-1 Specialist Chassis, only 2eD
-[ RECORD 7 ]-----+
critical_injuries | 6
-[ RECORD 8 ]-----+
critical_injuries | Secondary Specialty: Weapons/Devices\r
                  | *Blaster Pistol Templates only 1eD
-[ RECORD 9 ]-----+
critical_injuries | Imperial Brainwashing\r
                  | \r
                  | No hands
```

Based on what I'm seeing, I'm not sure people use the field exactly like you're describing, and I'm also not sure how we could migrate the data into a more structured format. I welcome suggestions however.

**Comment by duffn** [comment]
I think a rank for talents would be good, but I'm questioning the quantity for weapons. I'll write issues for both and see where it goes from there.

I completely agree on the crits now.

Thanks for the response.
