### ISSUE TITLE
Multiline character names break list group styling

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#119]
If a character has a name that spans more than a single line, the list groups styling breaks.

<img width="500" alt="Screen Shot 2019-12-16 at 3 20 19 PM" src="https://user-images.githubusercontent.com/3457341/70954865-28009c80-202c-11ea-97f0-5c6b87ada0c3.png">

**Comment by sparkertime** [comment]
A longstanding issue with the site that I have never made time for. Would love to see a fix roll in for it
