### ISSUE TITLE
Private characters

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#12]
Suggested at https://community.fantasyflightgames.com/index.php?/topic/178163-announcing-swsheetscom/#entry1635985

**Comment by bknowles** [comment]
Would there also be an option for semi-private characters?  I.e., anyone who has the URL can see it, but the URL is not easily guessable.  I'd like to be able to post some of my characters and share them with others in my group, but they shouldn't have to have accounts on the site to see them, and I wouldn't necessarily want to share those characters in an obvious and public manner.

**Comment by sparkertime** [comment]
@bknowles Hmm. At least at first I'd probably only do public and private (aka creator-only). Right now my character URLs are pretty easily guessed since they are just an incrementing integer.

But if this is going to work in conjunction with #13 then I have to have _some_ model of sharing in place, and your suggestion seems pretty straightforward. I'll marinate on this a bit longer, but I'm inclined to plan on your suggestion for the long term.

**Comment by bknowles** [comment]
Fair enough.  Thanks again!

**Comment by duffn** [comment]
@sparkertime I can’t really find any discussion on this and it was requested again on Reddit. Why the `wontfix`?

**Comment by sparkertime** [comment]
I am not strongly opposed but I do not think the complication of it is
worth the work. Hard for me to see a good use case for private characters,
and I think the site has benefited from being public.

If you want to add it, go for it though
