### ISSUE TITLE
Use static asset compilation with Webpack

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#127]
## Description

It would be nice to use Phoenix's current method of static asset handling: https://hexdocs.pm/phoenix/deployment.html#compiling-your-application-assets. I don't think this is critical, but should help with number of requests for static assets and asset size. 

It will add another, albeit small, step to building the application.

## ACs

_Reference a newly generated Phoenix 1.4 application for reference._

- Update all references to static assets in templates to use `Routes.static_path`.
- Alias `Routes` to `EdgeBuilder.Router.Helpers`. (This is new for 1.4: https://github.com/phoenixframework/phoenix/issues/2632#issuecomment-364470677)
	- Update code where necessary to account for this; i.e. `character_path`.
- Add necessary Node and Webpack setup.
- Add new compilation directions to README and `ansible-swsheets` (? on the second one, I haven't looked at this yet).

**Comment by sparkertime** [comment]
I'm not wild about installing and running Node in our production environment - it's more memory pressure on deploys and another dependency (one I probably need to keep more current than Erlang, which I've updated about every two years).

Our stylesheets and JS sizes are marginal when compared to the Bootstrap CSS & JS. I know less about what webpack does with images, but I could be talked into that if there's a painpoint there.

Ultimately though, if this is something that matters to you, I'll make it work in prod. :)

**Comment by duffn** [comment]
Maybe this ties in to #86 where the app is built prior to deploying to the server. Though, yes, I agree it's not critical as stated, but could be a niceity. Maybe I'll just test out some Lighthouse scores on Heroku just for fun to see if it is even worth the effort.

**Comment by duffn** [comment]
I played around with this a bit and have a completely non-working branch here: https://github.com/duffn/swsheets/tree/duffn/static-assets. I think this is going to be a bigger lift than I thought.
