### ISSUE TITLE
Format code with mix format

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#128]
## Description

I've been turning off format on save in VSCode because I didn't want the auto-formatter throwing too much noise in PRs. But, I think we should format all of the code according to convention.

## ACs

- Format all of the Elixir code with `mix format` in one big PR. https://hexdocs.pm/mix/master/Mix.Tasks.Format.html
- Stretch goal: introduce something like a [pre-commit](https://pre-commit.com/) hook to auto format or even something in CircleCI to check formatting on PRs.

**Comment by sparkertime** [comment]
This sounds fine to me, no objections
