### ISSUE TITLE
Dockerize applicaton for local development

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#129]
## Description

It would be a nice developer experience and slightly less barrier to entry if the application were run in Docker locally.

## ACs

- Setup local Docker environment with docker-compose to run application.
- Allow running of mix tasks inside of the container.

**Comment by sparkertime** [comment]
If this would just be for local dev, that is fine with me. I would prefer
not to run Docker in prod but I could be talked into it.

**Comment by duffn** [comment]
Yep! Local only was the plan for now.
