### ISSUE TITLE
GM Mode

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#13]
An interface where a GM can define a "party".

This interface shows
- Key statistics about that party (wounds, strain, XP, gold)
- Links to full character pages

**Comment by Amanal** [comment]
Be nice to invite players to enter and keep the info up to date too

**Comment by bknowles** [comment]
Agreed.  This could impact private characters (#12), however.

**Comment by sparkertime** [comment]
As a GM, I would want to see a short summary of each character (wounds, strain, selected skills[1], XP, credits, gear). I would also want a way to grant XP to these characters, but that would require some kind of permissions model and could be a fast-follower.

1: A couple of things could work here. An auto-complete box that adds the skill upon completion would work. As a GM though, I usually just want the answer to "In what skills is this character better at than any other character in the group?" - it'd be dope (if challenging) to figure that out automatically

**Comment by duffn** [comment]
I had the GM in one of my games get very excited when I mentioned the above potential to him.

**Comment by duffn** [comment]
Something like this would be handled under #32. Starring will allow you to see a list of characters and vehicles along with their key stats.
