### ISSUE TITLE
Print a Character

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#14]
Likely shelling out to ruby/prawn to print.

**Comment by bknowles** [comment]
Would this mean that the output would look something like the FFG character sheets?  Or would you go with something more like OggDude's format instead?

**Comment by sparkertime** [comment]
@bknowles Closer to FFG. I have a prototype that outputs this: https://github.com/citizenparker/swsheets/blob/pc_sheet_prototype/PCSheetPrototype.pdf but it need a lot of work still. The design is intended to be a bit more compact than FFG's and is based on my [compact NPC Sheet](http://rollcasual.com/post/117043045728/tools-you-can-use-compact-npc-character-sheet).

**Comment by bknowles** [comment]
Hmm.  I can't seem to get that to render or download.  But the compact NPC sheet looks good.  Different, but good.  Thanks again!

**Comment by sparkertime** [comment]
Just a note here in case anyone see this - work for this is in an entirely separate repo, [starkiller](http://github.com/citizenparker/starkiller). The goal is to have Elixir shell out to this Ruby script and pass all needed arguments in a JSON blob.
