### ISSUE TITLE
Update CORS settings in prod

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#150]
Something in prod is disallowing a link to  https://stackpath.bootstrapcdn.com/bootswatch/3.4.1/flatly/bootstrap.min.css . Possible culprits include NGINX but then I'm not sure why Google Fonts would work and not that CSS file.

**Comment by duffn** [comment]
Random article: https://enable-cors.org/server_nginx.html

**Comment by duffn** [comment]
This is fixed under #163.
