### ISSUE TITLE
Move application and database to new DO Droplet with Dokku

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#163]
I've decided to do this simply for the east of deployment and maintenance.

## Switchover Steps

- [x] Update `WEB_HOST` environment variable in Dokku after testing.
- [x] Setup Cloudflare in preparation for new site. #177 
- [x] Update maintenance page with estimated downtime. https://github.com/swsheets/maintenance-page
- [x] Test new site under separate domain that I already have pointed there.
- [x] Point DNS to maintenance page so no new items are created.
- [x] Take a full backup of the database.
- [x] Restore the database to new Droplet.
- [x] Point DNS at the new site to turn off the maintenance announcement and turn the site back on.
- [x] Smoke test new site.

## Notes
- Create DO setup with Dokku for testing.
	- Point a whole domain at this so we can ensure everything works before going live.
- Overwrite the database upon restore because I'll be testing.
- Time this whole thing so we can estimate how long it's going to take.
	- The backup of the current DB and copying and restoring it to the new server really takes only 2 minutes (knock on wood).

Of course, I'm going to test this on the environment first and ensure the process runs smoothly.

@sparkertime Would love to pair up with you on this when the time is right. What else am I missing here?

This will close
- #130 
- #86 
- #150

**Comment by sparkertime** [comment]
I think this makes sense to me. When I've had to take major maintenance windows, I've posted a notice in advance like in this commit c66d75772bf048c8f4a0c1336df136638bad42ac . 

I'm happy to wake up early on some Saturday morning (or _very_ early on a Sunday) and pair on this

**Comment by duffn** [comment]
I'm reading up a bit on Heroku automated certificates and it seems a bit of a pain compared to Cloudflare, so I may be having CF handle DNS, SSL, the www->bare redirect and also caching. https://support.cloudflare.com/hc/en-us/articles/205893698-Configure-Cloudflare-and-Heroku-over-HTTPS

**Comment by duffn** [comment]
I'm questioning myself now. I'm not sure another $10/month justifies switching to Heroku. I'm considering - and have been testing quite a bit - a DO droplet with Dokku, so I can get the cost savings of DO and the easy of deployment of Heroku. 

Either way the switchover checklist stays the same.

**Comment by sparkertime** [comment]
As always, it's up to you. I've never used Dokku, but a quick skim of the docs reads like you'll have the same memory pressure issues that deploys currently have (probably marginally worse since you're running Dokku & Docker too, but the latter doesn't contribute significantly to RAM IIRC).

While it seems like the effort of running `script/deploy` vs `git push dokku` is about the same, there are definitely pros & cons. Troubleshooting and fixing a failed deploy may be harder with Dokku, but Elixir / Erlang upgrades become a lot easier.  Probably not a clear winner so it comes down to personal preference, and I'm happy to help with whatever you pick.

**Comment by duffn** [comment]
Yeah, that's a good point about debugging. I know we talked about deploying with Ansible being a slight pain, so was looking for something different, but maybe it's not even necessary. Maybe I'm chasing something here that we don't even want.

For reference, Dokku deploys look somewhat like this:
<img width="949" alt="Screen Shot 2020-01-16 at 6 54 38 AM" src="https://user-images.githubusercontent.com/3457341/72530748-432e1a00-382d-11ea-92d9-ea0b479f8050.png">

**Comment by sparkertime** [comment]
That's CPU usage, right? RAM is the pressure point, I've never looked at CPU usage but then I've never had a reason to

**Comment by duffn** [comment]
Ah, indeed. I've just enabled the enhanced metrics on this test server and will take a look at memory.

**Comment by sparkertime** [comment]
If you can deploy latest master to it and the deploy succeeds, that's probably all the metrics you need to say it works well. That said, make sure that whatever you have captures both RAM and swap. If those look good, then you should definitely make the switch (and find out whatever voodoo magic Dokku is doing to make it work)

**Comment by duffn** [comment]
Yes, I've deployed dozens of times to it at this point without an issue.

**Comment by sparkertime** [comment]
Neato! Then I'd still advise taking a look at it but it sounds like you
have a winner.

**Comment by duffn** [comment]
This is complete without incident. I'll keep an eye out for the next day or two and then delete the old DO droplet.
