### ISSUE TITLE
Word filter :(

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#17]
I was hoping to put this off until later, but I already have some pretty profane character names on the site. Le sigh.

**Comment by sparkertime** [comment]
Random thought - if I implement #12 and also add an email verification, I could make all characters private-only until someone had verified their email. In both of the profane entries so far, they were under accounts with bogus emails. I'd rather solve this problem that way than add an exhaustive word filter.

**Comment by bknowles** [comment]
Exhaustive word filters will ultimately fall down anyway.  As you tighten the iron grip to prevent more and more stuff slipping through, you wind up getting more and more false positives.
