### ISSUE TITLE
Split out Weapons/Armor, Personal Gear, and Assets/Resources

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#19]
This is actually how the FFG charsheet tracks this stuff, so adding it would be in keeping with the project.

**Comment by bknowles** [comment]
+1

Longer-term, it would be nice to be able to automatically track encumbrance, cost, number of items (stacked or otherwise), where they are located, if they are equipped, etc....  But that's longer-term.  ;)

**Comment by sparkertime** [comment]
After further research I learned that only the EotE character sheet in the Core Rulebook includes the third "Assets and Resources" section. The AoR and FaD sheets dropped it, and even the EotE character sheet that FFG published online dropped it. As such, I'll drop it as well.

I'll rename "Gear" to "Personal Gear" and add another entry for "Weapons & Armor" later today.

**Comment by sparkertime** [comment]
So I've done the work as described above, but the more I think about it, the more I think something like "Assets & Resources" makes sense. I think characters often need some way to say "I own this even if I'm not carrying this right now" and I wonder if it was dropped from the charsheets because of space concerns.

The explicit goal of SWSheets.com is to adhere to the charsheets as published with few exceptions. However, this feels like an exception worth making. @bknowles what do you think about adding "Assets and Resources" ?

**Comment by bknowles** [comment]
IMO, you should use whatever you think works best.  I like looking at what FFG does as a starting default, but if we can come up with something better, then I think we should definitely be up for that.

So long as you've got a way to indicate gear that you own but that is stored somewhere else versus what is currently carried but not equipped versus what is carried and currently equipped, I don't see that it matters much how you treat that.  A separate category would be an easy way to handle that, as would a separate column in the overall "gear" or whatever category.

Do you slice the cake horizontally or vertically?  ;)

**Comment by sparkertime** [comment]
Good advice, thanks! I went with Assets and Resources.
