### ISSUE TITLE
Arrow buttons on Lightsaber broken

### ISSUE THREAD

**Issue by th3jesta** [citizenparker/swsheets#201]
I'm getting the following in the console when I click on the arrows next to Lightsaber. I assume that these arrows are to change the base characteristic for the skill, but nothing happens when I click or tap the arrows.

```
Uncaught TypeError: o.size is not a function
    at s (app-8763b80c3b7c7e4bd67530bfd51d0f85.js?vsn=d:1)
    at HTMLAnchorElement.<anonymous> (app-8763b80c3b7c7e4bd67530bfd51d0f85.js?vsn=d:1)
    at HTMLAnchorElement.dispatch (jquery-3.4.1.min.js:2)
    at HTMLAnchorElement.v.handle (jquery-3.4.1.min.js:2)
```

Tested in Vivaldi, Chrome, Firefox, Edge (non-Chromium), and Chrome on Android.
![image](https://user-images.githubusercontent.com/38670315/73041413-60fe0f00-3e2b-11ea-87d5-b3ef43404385.png)

**Comment by duffn** [comment]
I very much appreciate the report! I'll be pushing up a fix shortly.

**Comment by duffn** [comment]
Thanks again! I've deployed a fix and tested successfully. Would you care to share you SWSheets username? I'd love to add you here: https://swsheets.com/thanks

**Comment by th3jesta** [comment]
Wow, thank you for the lightning-fast response! I have confirmed it is working on my end as well. My username is jessewisener.

**Comment by duffn** [comment]
You're all set. Please don't hesitate to report if you notice something else. Thanks again!

<img width="622" alt="Screen Shot 2020-01-24 at 7 39 52 AM" src="https://user-images.githubusercontent.com/3457341/73077132-caf2d480-3e7c-11ea-94b4-0267eaefa972.png">
