### ISSUE TITLE
Add field that displays in monospace font

### ISSUE THREAD

**Issue by LtChae** [citizenparker/swsheets#254]
Spec trees are a big ask and a lot of work, but many users have compromised by putting ascii talent trees in their sheets:

```
Prophet
| XP | A | B | C | D |
|----|---|---|---|---|
| 05 | X | X | O | O |
| 10 | O | X | O | O |
| 15 | O | O | O | O |
| 20 | O | O | O | O |
| 25 | O | O | O | O |
```

These don't turn out very well in the variable width font used on the sheet:
<img width="168" alt="Screen Shot 2020-04-24 at 11 47 04 AM" src="https://user-images.githubusercontent.com/5122881/80231435-5c5f1780-8621-11ea-99c1-e2c010d1460f.png">
(This example is the best I could make taking the width change into account)

If we could add an additional field that could be edited *and* displayed in a monospace font, we could make more detailed and readable spec sheets.

**Comment by duffn** [comment]
Oh, that's very interesting! To be honest, I didn't know that was a common use case.

Would you be able to provide a link to a sheet that does this so I can take a look?

**Comment by LtChae** [comment]
Sure can! Several, actually. People generally use the notes section I've found.

https://swsheets.com/c/gm2pbzuow-rikkit-vr-krit
https://swsheets.com/c/owgqofguy-ciessa-bolemen
https://swsheets.com/c/xsw4yvkcq-na-tina
https://swsheets.com/c/ie5dnutvj-wek-vocid-chyth

**Comment by LtChae** [comment]
A few more. As you can see, there are a couple of basic forms that people copy paste from sheet to sheet:
https://swsheets.com/c/wihg4yax6-sfl---b33-fy
https://swsheets.com/c/nhqhcleom-tazrin
https://swsheets.com/c/xb5a8zxqm-it%C5--roda

**Comment by duffn** [comment]
Excellent, thank you for the examples!

**Comment by duffn** [comment]
For open discussion:

1) Should we just make "other notes" a monospace font and call it good? That would be nice for users like the above that already have spec sheets in that field.
2) Should we create an entirely new field that is solely meant for monospaced items like the spec sheets?

**Comment by davidagnome** [comment]
I've added classes to enable this in the future in #286 -- which would be great to implement alongside the separate Print styles (hope to make the sheets as beautiful printed as they are on desktop).

**Comment by duffn** [comment]
Amazing, thank you for the contribution! I'll take a look.

**Comment by davidagnome** [comment]
Haven't added the CSS yet for monoapace. Still need to add the classes to
the editor view then add the CSS.

**Comment by duffn** [comment]
Awesome, will wait for that.

**Comment by davidagnome** [comment]
Added the necessary CSS (improves print media stylesheets as well as a monospace class using multi-OS safe fontstack) in PR #287

**Comment by duffn** [comment]
Deployed, thanks @davidagnome!
