### ISSUE TITLE
Doesn't recognize email 

### ISSUE THREAD

**Issue by BetsyBaer** [citizenparker/swsheets#276]
Hello! I have a username with SWsheets, but forgot the password. When I put in the associated email, it said I hadn't created an account yet. 

How to I recover my email/password? I have the my username.

**Comment by duffn** [comment]
Hi, sorry to hear that! Can you tell me your SWSheets username?

**Comment by BetsyBaer** [comment]
Yes BetsyBaer is the username

**Comment by BetsyBaer** [comment]
Hello!

I wanted to know if the email associated with my account on SWSheets was
ever found?

Thanks!
BetsyBaer

**Comment by duffn** [comment]
I will respond via email.

**Comment by duffn** [comment]
This should be resolved via email.

**Comment by BetsyBaer** [comment]
thank you! It's fixed!
