### ISSUE TITLE
500 Error When Attempting to Get Password Reset Email

### ISSUE THREAD

**Issue by GrandAdmiralUehara** [citizenparker/swsheets#284]
I forgot my username and password for my account and was attempting to get a password reset email sent to my inbox. However, every time I insert my particular email address, trying to continue results in a 500 error. I even made another account with a different email and confirmed that this error does not occur with other email addresses, so it seems that the email address information of my original account is somehow bugged.

**Comment by duffn** [comment]
I’ll take a look. Is this username the same as your SWSheets username?

**Comment by GrandAdmiralUehara** [comment]
Yes, GrandAdmiralUehara is my username on SWSheets. I was eventually able to guess the username and password, but attempting to use the password reset feature to send the email still results in a 500 error when I enter the email for my main account.

**Comment by duffn** [comment]
Okay, I’m glad you’re able to get in. I’ll see if there’s anything I can dig up.

**Comment by MichaelNotEric** [comment]
@duffn I am seeing this error as well.

**Comment by duffn** [comment]
Is your username on SWSheets the same as here?

**Comment by MichaelNotEric** [comment]
> Is your username on SWSheets the same as here?

Yes it is, sorry I didn't see your reply right away.

**Comment by mbfranc** [comment]
@duffn I'm seeing this error as well... Username is mbfranc

**Comment by duffn** [comment]
This should be fixed now. Thanks for reporting.
