### ISSUE TITLE
Support Force and Destiny Characters

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#29]
Let's do #28 first before tackling this one.

**Comment by bknowles** [comment]
I'm in an F&D campaign now, so that would get my vote for priority.

Just sayin'.  ;-)

**Comment by sparkertime** [comment]
@bknowles I'm a bit out of the loop on F&D sadly - my players trust the blasters at their sides rather than hokey religions and ancient weapons. :) Has a final character sheet been published, or will that be part of the final release of the core rulebook?

If there is a final version, can you point me to a good example of a filled-in charsheet? I see https://images-cdn.fantasyflightgames.com/ffg_content/StarWarsRPG/force-and-destiny/support/Force-and-Destiny-Character-Sheet.pdf but I'm not clear on what the proper content on the second sheet should look like.

If there's not been an officially final version, then sadly I'm going to hold off until there is. I definitely want to provide F&D support, but I don't want to do the work twice. That should be no later than Gencon, right?

**Comment by bknowles** [comment]
Nothing can really be declared official or final until the CRB comes out, but I'm happy to share scans from my copy of the beta, if you like.

So far as I know, there hasn't been an official publication date set for F&D CRB, but I believe that the community does generally expect it to ship at or just before Gencon.

As for the content on the second sheet, I'm not convinced that anyone really knows.  I make my best guess based on what I think it means, but I can't be sure.

**Comment by sparkertime** [comment]
I think I've relented on this a bit, here's why: I would really like to get to https://github.com/citizenparker/swsheets/issues/15 as soon as possible. That means I need pretty good support for all the different kinds of characters and vehicles pretty soon. So I don't think I can wait until Gencon to add FaD support.

**Comment by sparkertime** [comment]
Apparently the lightsaber skill can be based off any characteristic in FaD based on which specialization you choose. _(deep sigh)_. That will complicate the interface a bit. Anyone know of other gotchas like that in FaD that aren't reflected on the character sheet?

**Comment by bknowles** [comment]
Yeah, sorry about that.  Each career has one combat-oriented specialization with a talent to let you do that.

I'm not aware of any other gotchas, but then I've been playing F&D for a while now and maybe I don't remember them.

I know that Morality is interesting, and it is possible to have all three of Obligation and Duty and Morality.  Morality can also go over 100, apparently.  If you're over 90, then you get +1 Max Strain Threshold, and if you're 100 or higher then you get another +1 Max Strain Threshold.

There's also Holocrons and Mentors.  With a Holocron, you can have one or two additional skills that are considered to be Career skills, so long as you own it.  But ownership of a Holocron can be shared amongst multiple members of a party.  With a Mentor, you get a five point reduction in the cost of buying any new base-level Force Powers, but only the base level power and not any of the upgrades.  Of course, you don't get the Mentor or Holocron bonuses during character generation.

Lots of other stuff, I'm sure.

**Comment by sparkertime** [comment]
This is ready to go! I plan on deploying it later today. I'll post here when its out. Woohoo!

Turned out to be a TON of work to make upgrades work correctly in my framework, sorry for the delays!
