### ISSUE TITLE
Recompilation generates a warning on any parameter-ized model

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#31]
`nofile:1: warning: redefining module Phoenix.Param.EdgeBuilder.Models.Character`

This is blocked pending a resolution to https://github.com/elixir-lang/ecto/issues/632. The good news is that this really only bothers me. =)

**Comment by sparkertime** [comment]
The fix for this is in Ecto's master branch, I just need to pull the latest version once there's a release newer than 0.12.0-rc on https://github.com/elixir-lang/ecto/releases

**Comment by chrisjpowers** [comment]
Is this still an issue? I don't believe I've ever seen that warning during development.

**Comment by sparkertime** [comment]
Nope, this is not an issue. The `mix.exs` file was already configured to pick up the newest version. Thanks for checking!
