### ISSUE TITLE
Add Commenting

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#33]
Users can comment upon a character sheet using basic Markdown syntax.

**Comment by bknowles** [comment]
:100:

**Comment by chrisjpowers** [comment]
Any users, or just character owners? This seems like inviting trouble without a lot of upside if you want to allow anyone on the site to comment on any character.

**Comment by sparkertime** [comment]
I was originally thinking any registered user. I have cooled to this idea though (this is why I removed the "Planned" label a few days ago). Having this limited to owner-only seems somewhat pointless. I'll close this in a few days unless someone objects.

**Comment by duffn** [comment]
I agree with the previous comment and am closing this one.
