### ISSUE TITLE
New Spcialisations

### ISSUE THREAD

**Issue by Amanal** [citizenparker/swsheets#39]
Can we add a new second/third specialisation?

**Comment by bknowles** [comment]
Minor typo in the title -- the word "Spcialisations" should either be "Specialisations" or "Specializations", depending on whether you go with UK or US English spelling.

Right now multiple specializations are handled just through descriptive text, but it would be nice to have better support mechanics to making that work.

**Comment by sparkertime** [comment]
Hi @Amanal , thanks for weighing in!

What would be the benefit of separating specializations into multiple text fields? I don't have plans to add any features that depend on someone's specializations, so this seems like it might just clutter up the interface.
