### ISSUE TITLE
Make a new Edge of the Empire logo

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#43]
While the Imperial Emblem is neat, it looks like a flower at low resolutions.

Definitely open to suggestions for other iconic SW logos/emblems which are appropriate to Edge.

**Comment by sparkertime** [comment]
I've mostly fixed this for now. It isn't perfect, but it is improved.

**Comment by bknowles** [comment]
What about using the typeface from http://www.sigmaecho.com/star-wars-logos-emblems-and-symbols-font/?  Would that help?

**Comment by sparkertime** [comment]
@bknowles Unfortunately, no. I'm starting from resolution-independent vector art, but I ultimately have to fit it inside an 18x18 pixel square. The Imperial logo is _much_ harder to see at 18px than the Jedi or Rebel alliance logos. The Empire had poor graphic designers. =)

I've taken one last stab by making something from scratch. It's actually closer to the Republic symbol now than the Imperial, but hopefully folks get the idea.

**Comment by bknowles** [comment]
Ahh.  18x18 pixel square.  Well, for those of us on HDPI machines, you could make that 36x36 and display at twice the resolution per inch.  ;)

For everyone else, I'm not sure I have any useful advice.  ;(
