### ISSUE TITLE
Figure out why the test suite is SOOOOO SSSLLLOOOWWWWW.....

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#45]
This isn't an inconvenience to anyone but me, but holy moley this is a slow test suite.

**Comment by bknowles** [comment]
Do you use Travis-CI or one of the other free-to-use services from https://github.com/ripienaar/free-for-dev/?

**Comment by sparkertime** [comment]
I don't. I should eventually set up Travis CI but right now I just run
tests locally before committing.

**Comment by pinfieldharm** [comment]
I just submitted a pull request that takes care of much of the slowness: https://github.com/citizenparker/swsheets/pull/51

**Comment by sparkertime** [comment]
Between this and https://github.com/citizenparker/swsheets/commit/a3cfbd785ae1d987464afe9259b343f9a12f912b the test suite is as fast as it will (reasonably) get.
