### ISSUE TITLE
Upgrades for Force Powers disappear on save.

### ISSUE THREAD

**Issue by TCArknight** [citizenparker/swsheets#52]
I am trying to add Force Powers to a character (Dev'rios Chol) and every time I try to add more than one upgrade for the Enhance power, all but the last Upgrade disappear upon saving the sheet.

**Comment by sparkertime** [comment]
Ack! I see your issue and I'm working on a fix for it today. I'm so sorry if you've lost work as a result.

Thank you SO much for reporting this, really appreciate it. When this is fixed I'll give you the Bug Reporter award on the site.

**Comment by TCArknight** [comment]
On 2015-09-18 07:47, Scott Parker wrote:

> Ack! I see your issue and I'm working on a fix for it today. I'm so 
> sorry if you've lost work as a result.
> 
> Thank you SO much for reporting this, really appreciate it. When this 
> is fixed I'll give you the Bug Reporter award on the site.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

Not a problem, glad to help out :)

I was about to open another bug as well that several of us have seen: 
There's no way to edit the Morality. Whenever shift from viewing to 
editing, the Morality box completely disappears. I'm having to list my 
Morality as well as my Obligation or Duty in the notes area instead.... 
:)

## Links:

[1] 
https://github.com/citizenparker/swsheets/issues/52#issuecomment-141442262

**Comment by sparkertime** [comment]
Ouch, embarrassing. Thanks for letting me know, and sorry for the issues around this. Force and Destiny is the only one of the three systems that I don't actually play, so I'm not running into these problems myself.

I have created https://github.com/citizenparker/swsheets/issues/53 to track that.

**Comment by sparkertime** [comment]
Follow-up question. I want to ask about this statement:

> I'm having to list my Morality **as well as my Obligation or Duty** in the notes area instead

Are you having issues with Obligation or Duty as well? Or are you saying you have all three simultaneously? Is that a supported thing that I don't know about, or is that a home rule?

**Comment by TCArknight** [comment]
With the Force and Destiny sheet, I'm not seeing a spot to enter either
Obligation or Duty (or both) in addition to Morality. 

I believe it's up to the GM, but I don't believe I've seen a campaign
where in addition to Morality, a character didn't have At least one of
Obligation or Duty and sometimes both. I'm in a game now on the FFG
boards where it's primarily F&D, but each character either has an
additional Obligation or Duty value. 

I remember seeing eking something specific in the rules about it and
that you couldn't get bonus XP or Credits from more than one source
(Obligation, Duty, or Morality) but I think it is called out that it's
possible in some games to have all three values. 

On 2015-09-18 08:25, Scott Parker wrote: 

> Follow-up question. I want to ask about this statement: 
> 
> > I'm having to list my Morality AS WELL AS MY OBLIGATION OR DUTY in the notes area instead
> 
> Are you having issues with Obligation or Duty as well? Or are you saying you have all three simultaneously? Is that a supported thing that I don't know about, or is that a home rule? 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/citizenparker/swsheets/issues/52#issuecomment-141450979
