### ISSUE TITLE
Weapons for ships not showing up

### ISSUE THREAD

**Issue by Kymrel** [citizenparker/swsheets#54]
Hi there, and thanks for an awesome resource.

There is a but with the way weapons for starships are displayed. When I enter the name of the weapon and hit save, the name is replaced with a number (0 for the first, 1 for the second weapon).

The bug can be seen here in this split-view jpeg:
http://i1363.photobucket.com/albums/r701/brjannjonasson/SWSheets%20error_zpsewhy2boe.jpg

**Comment by sparkertime** [comment]
Thanks for reporting this and so sorry you ran into an issue. I will take a
look at this tonight and hopefully get it fixed then.

**Comment by Kymrel** [comment]
Not a problem mate, thank you for this excellent website. No hurry at all, just doing my duty as a responsible user pointing it out :)

**Comment by sparkertime** [comment]
@Kymrel All fixed. Thanks for reporting the bug - gave you credit on the site.

**Comment by Kymrel** [comment]
That was fast! Awesome work man, thanks so much!
