### ISSUE TITLE
The case for custom skills

### ISSUE THREAD

**Issue by themensch** [citizenparker/swsheets#63]
Hi Team,
  I read on your FAQ that you don't plan to include custom skills, and while I agree with your assessment in part, but please hear me out.  

  This is a widely-used tool by people who play their game in different ways.  If the level of effort involved to implement custom skills isn't terribly difficult, it would be a nice feature to have.

**Comment by sparkertime** [comment]
Thanks for the suggestion. Custom skills would be a problem for several different screens, especially if I ever finish the work for exporting to PDF. I'd really prefer not to support them. I'll leave this open in case others want to voice their support for them, however.

**Comment by themensch** [comment]
How do you intend to support new custom skills introduced in supplements?  Cybernetics, for example, is introduced officially in an adventure module produced by FFG.  I think we're going to run into this as the lines progress.

**Comment by sparkertime** [comment]
I'm going to close this since I haven't heard any other voices of support for this in the year or so since it was opened. Thanks for the suggestion though! If you feel passionate about this and want to submit a pull request that implements this cleanly, please do.
