### ISSUE TITLE
Collapsable skills table that only shows trained skills

### ISSUE THREAD

**Issue by themensch** [citizenparker/swsheets#64]
Feature suggestion:

To save space on the screen, perhaps a toggle could be implemented between showing all skills and trained skills.

**Comment by sparkertime** [comment]
That's an interesting idea, but I really like the clean simplicity of the skills view right now and I'm leery of adding more components to it

**Comment by themensch** [comment]
I agree that simplicity is the ultimate elegance here, but I think a simple checkbox or switch would be pretty unobtrusive and nix one of the bigger complains I hear from people I direct to this site.
