### ISSUE TITLE
Knowledge Warfare 

### ISSUE THREAD

**Issue by KaelW** [citizenparker/swsheets#67]
There seems to be a Knowledge skill missing, namely Knowledge Warfare which I believe was introduced in the AoR core. So what would it take to have the skill added? Or in lieu of that how about a blank Knowledge skill slot that we could use to fill it in?

**Comment by sparkertime** [comment]
Hmm, it should appear when you change the character's system to Age of
Rebellion. Can you send me a link to a character where that isn't happening?

Thanks!

**Comment by KaelW** [comment]
I was not aware that you had to have it set to Age of Rebellion. I had it set to Force and Destiny since the starting career was from that game and I added a AoR specialization later.

**Comment by sparkertime** [comment]
Hmm, that's a tricky situation since the systems don't share the same skills and diverge in a few other ways. For now, you may have to use the "Notes" to capture that if you want to stay in Force and Destiny.

**Comment by themensch** [comment]
Another case for custom skills!
