### ISSUE TITLE
Add checkboxes to account for changing Status

### ISSUE THREAD

**Issue by themensch** [citizenparker/swsheets#69]
Having the ability to tick boxes to count wounds and strain would be fantastic.

**Comment by bknowles** [comment]
How does this relate to #72 ?

**Comment by sparkertime** [comment]
I'm not sure I follow this one. Are you suggesting a check box for each possible strain or wound?

**Comment by themensch** [comment]
That's right, let me explain.  As a play aid, it would be handy if the sheet would render checkboxes, possibly in a grid underneath or near the stat they're tracking.  This would work equally well for Limited Ammo.

**Comment by sparkertime** [comment]
I really appreciate the suggestion but I'm going to close this issue. [Some characters](http://swsheets.com/c/opg9x6sja-chewnawa) have way too many strain and wounds to represent with checkboxes.

I'll stick with the +/- buttons for now.
