### ISSUE TITLE
Starship/Vehicle handling

### ISSUE THREAD

**Issue by Tramp-Graphics** [citizenparker/swsheets#70]
There is an issue with the Handling block on the Vehicle creation sheet. the minimum Handling score it allows is 0 yet almost all Silhouette 5 or above ships have handling ratings in the negative numbers, sometimes as low as a -5 and below. Is there any way to fix this issue?

**Comment by sparkertime** [comment]
Thanks for the report. Definitely a bug and pretty straightforward to fix,
thanks for reporting it. Any idea on what the lowest value is on handling?
I can dig it up but that will take a day or two.

If you want bug credit on the site, let me know your swsheet username.
Thanks again for the clear, detailed report!

**Comment by Tramp-Graphics** [comment]
I don't know the absolute lowest it goes, but I do know that the CEC Deep Space Recovery Vessel L-2783 has a Handling rating of -4, as does the Sorosub Portable Store KRI-80, both from Special Modifications. Pretty much every capital ship has a negative number for a handing rating. To be on the safe side, I'd set the negative modifier as low as the positive modifier currently is high.

**Comment by sparkertime** [comment]
Sounds good, thanks! I'll have that change deployed tomorrow.

**Comment by Tramp-Graphics** [comment]
Oh, and the Username is TrampGraphics (unfortunately, I couldn't add a space in my user name, or a dash.).

**Comment by sparkertime** [comment]
All fixed and credit given on the site. Thanks again!
