### ISSUE TITLE
Active Vehicle Damage 

### ISSUE THREAD

**Issue by Tramp-Graphics** [citizenparker/swsheets#72]
The character sheets have the ability for the Strain and Wounds current Thresholds to be adjusted using a +/- toggle. Is there any chance to have that added to the current Hull Trauma and System Strain Thresholds for Vehicles?

**Comment by bknowles** [comment]
How does this relate to #69 ?

**Comment by Tramp-Graphics** [comment]
Actually, I didn't even know about # 69, but character sheets have the ability to keep track of current wound and strain, but starships and vehiicles don't have the capacity to keep track of current Hull trauma and System Strain . It would be good if you could do so. 


trampgraphics@aol.com




-----Original Message-----

**Comment by sparkertime** [comment]
I am not adding new features to the site these days, but this would be a welcome pull request if anyone sees this and wants to take a stab at it!
