### ISSUE TITLE
Adding skill modifiers to skills feature

### ISSUE THREAD

**Issue by JorArns** [citizenparker/swsheets#73]
Would it be possible to add skill modifiers (boosts, minus setbacks, force die) to the skill dice to show everything that the player would roll? The reason I ask is that Oggdude's character generator does this and it is immensely helpful. 

Example: A character with the Sleight of Mind talent would roll a boost die with their stealth skill.

**Comment by sparkertime** [comment]
I think there's too many edge cases with those talents to consider this. For instance, Sleight of Mind does not apply in checks involving force-immune sources. It would be awfully complicated to try and represent that.

Thanks for the suggestion though! I would still welcome a pull request that implements this if you can do so without cluttering the interface
