### ISSUE TITLE
Deploy Artifacts

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#86]
(cross issue with ansible-swsheets)

I've maxed out the size of my swapfile on my DigitalOcean droplet. Either SWSheets gets more expensive to run, or we precompile the app and then deploy to DO. We run fine on memory except during compilation, so this should almost certainly fix the problem.

**Comment by duffn** [comment]
I sent up a branch for Heroku just for fun on all free bits. I don't know what the DO droplet looks like, but I suppose SWSheets could run on a hobby dyno and on the hobby dev PostgreSQL (?). That's $16/month. I suspect that's more expensive that DO, but deploying is a snap and there's no server management. Though there are other limitations: https://hexdocs.pm/phoenix/heroku.html

- https://github.com/swsheets/swsheets/compare/master...duffn:duffn/heroku?expand=1
- https://boiling-escarpment-56682.herokuapp.com/

**Comment by sparkertime** [comment]
I originally wanted to host on Heroku but DO costs me $6 / month in total. Since I pay for SWSheets out of pocket, cheaper wins.

**Comment by duffn** [comment]
Very understandable!

**Comment by duffn** [comment]
This is fixed under #163.
