### ISSUE TITLE
Delete does not delete

### ISSUE THREAD

**Issue by Alfiethesquire** [citizenparker/swsheets#92]
Why doesn't the delete button delete stuff
What's the point in having a delete button if it doesn't work

**Comment by sparkertime** [comment]
Can you be more specific? Are you trying to delete a character, vehicle,
attachment, talent, force power, or force power upgrade? If it is a vehicle
or character, from what screen are you trying to delete?

Also, info on your browser and version would be useful too.

Thanks!

**Comment by Alfiethesquire** [comment]
Oh sorry, I haven't made any vehicles but when ever I try to delete a character it just doesn't, talents and force powers are fine. I tried deleting them from both screens, doesn't work
Also btw I'm using safari on my iPad to do this.

**Comment by Alfiethesquire** [comment]
Citizen Parker? 🙄

**Comment by sparkertime** [comment]
Interesting, I was just able to reproduce this. I'll get a fix out pronto and give you credit on the site. Thanks for the heads-up, stay tuned for a resolution.
