### ISSUE TITLE
Text Only

### ISSUE THREAD

**Issue by KayserSosa** [citizenparker/swsheets#93]
Appears to only be loading with text only.  The graphics are no longer loading.

**Comment by KayserSosa** [comment]
![capture](https://user-images.githubusercontent.com/19256254/33810107-8cdf2e46-ddc6-11e7-8ae7-49e77aa02043.JPG)

**Comment by sparkertime** [comment]
Huh, interesting. Looks like you closed this so I'm guessing it's not still happening - if it is, please let me know what browser you're using and if you'd done anything like disabled javascript, etc. Everything looks fine to me.

**Comment by KayserSosa** [comment]
Sorry shouldn't have been closed.  I use Chrome.  Just opened it on IE and no issues.  I think Chrome was recently updated.  Looking into Javascript in chrome.

**Comment by KayserSosa** [comment]
Javascript is enabled on Chrome version 62.0.3202.94 (Official Build) (64-bit)

**Comment by KayserSosa** [comment]
I made no changes to Chrome.

**Comment by sparkertime** [comment]
Interesting - I've tested on that version of Chrome and I see no issues and haven't heard similar issues. Do you mind loading SWSheets with the Developer Tools "Network" tab open? (right click the site, choose "Inspect," then "Network," and refresh the page). If you could send me a screenshot of what you see at that point, that could help. It should look something like this:

<img width="1321" alt="screen shot 2017-12-11 at 7 20 36 am" src="https://user-images.githubusercontent.com/128267/33833100-1d6d5d52-de44-11e7-962d-efd77e2e4495.png">

**Comment by KayserSosa** [comment]
![untitled](https://user-images.githubusercontent.com/19256254/33837058-cff41306-de50-11e7-8757-e65c0c32e8ef.jpg)

If you need anything else, let me know.  Thanks for taking a look at this.  I'm sure something was turned off or on and I didn't realize it.

**Comment by sparkertime** [comment]
Great, thanks. I'll dig into this tonight - if I can indulge one last favor in the meantime, does this issue still happen if you load the page with your Chrome extensions disabled? (If you haven't enabled them for Incognito mode, opening an incognito tab is faster than disabling each one individually)

Thanks!

**Comment by KayserSosa** [comment]
Just disabled them and refreshed.  Same.  The page had worked normally with the extensions prior to 12/7 when this started happening.

**Comment by sparkertime** [comment]
Sorry, I can't crack this one. Here's the best I can do.

It looks like loading the page stops after that red line you posted, the one with `partner_id` `sub_id` etc. I have no idea what that is - nothing in SWSheets loads anything like that.

A Google Search seems to indicate that may be related to some Chrome extensions - see [this link for a couple different extensions that load it](https://productforums.google.com/forum/#!topic/chrome/UbToGGmN-MM;context-place=forum/chrome).

**Comment by KayserSosa** [comment]
I think I found the red line issue.  The Tampermonkey v4.4 Chrome extension.  I disable it and restart the browser and the page is working again and the red line is gone.

**Comment by KayserSosa** [comment]
![untitled](https://user-images.githubusercontent.com/19256254/33894783-713ba7dc-df24-11e7-80da-d5e460256d88.jpg)

Issue is still going on.

**Comment by KayserSosa** [comment]
![untitled](https://user-images.githubusercontent.com/19256254/33894858-a600d3fc-df24-11e7-93bf-d2fd66d18818.jpg)


This error appears.

Waterfall
24 requests ❘ 40.5 KB transferred ❘ Finish: 672 ms ❘ DOMContentLoaded: 469 ms ❘ Load: 702 ms

Console
What's New
Request blocking



top
Default levels

﻿swsheets.com/:1 Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

**Comment by KayserSosa** [comment]
Just checked on Firefox and IE, main page loads fine but when you click on the login link it jumps to only text.

**Comment by KayserSosa** [comment]
Does the site use VBScript?

**Comment by KayserSosa** [comment]
I think I have finally narrowed the issue down to my router.  pfSense, it just got an update the other day when this started.  I tried the site on my phone on my network then off my network and it works off my network.  Can you tell me what scripting or other stuff the site might be using that could possibly be blocked?

**Comment by sparkertime** [comment]
SWSheets doesn't use VBScript, it only uses CSS and Javascript. Most CSS and Javascript is hosted on swsheets.com itself, but some CSS is loaded from googleapis.com and some JS from maxcdn.com

**Comment by KayserSosa** [comment]
I have confirmed the issue is my pfSense router, no fix in sight.  Up to you if you want this left open or closed.  Thanks for the help.  If I find a fix I'll post it.

**Comment by KayserSosa** [comment]
The issue is related the squidGuard Proxy installed on the pfSense router.  Still troubleshooting it, but with the proxy off the site works.

**Comment by KayserSosa** [comment]
FYI, the error on Chrome page, below, is from SaveFrom.net helper, a YouTube downloader I have installed that requires the extention TamperMonkey.

VM574:34278 Refused to connect to 'https://cr-input.mxpnl.net/data?_channel_id=&_partner_id=39571&_sub_id=0000&_app_version=1.0.23&_app=cs-dca' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by KayserSosa** [comment]
After following the setup of the proxy using this video, the site appears to be functioning normally.

Issue is the Transparent HTTP Proxy.  Not sure how to set it up for it to go through the proxy, but if the site is added to the " Bypass Proxy for These Destination IPs" section, it works by bypassing the proxy and leaving it up for everything else.

PFSense Series #02 - How to setup SQUID & SquidGuard
https://www.youtube.com/watch?v=OrB2i2btceI
