### ISSUE TITLE
Add boosts and setback removals to skill list and weapons

### ISSUE THREAD

**Issue by LtChae** [citizenparker/swsheets#94]
It would be handy to note permanent boosts, setbacks, and setback removals on applicable skills. Maybe a text box near the skill rank using one of the common symbol notations. (The Roll20 sheet has some good examples of this.)

**Comment by sparkertime** [comment]
Sounds like a neat idea. I'm not adding new features to SWSheets these days but if someone sees this and wants to submit a pull request, be my guest!

**Comment by zactru** [comment]
Honestly this request would make this character sheet perfect.  It would be amazing to have a small text box to the right of the dice (green/yellow) in the skills section for each skill.  One of the biggest parts of the FFG Star Wars RPG's is all of the boosts (blue die, Force die, remove black die, advantage).  As you level, it becomes very hard to track how many bonuses/boosts you have for each skill.  Can you please add this to the sheet?  I would do a pull request but I don't know the language you used to create this sheet.  I have 7 players that would use this, and I'd be very willing to push this on social media as the Best FFG Star Wars Character sheet out there!  Please!

**Comment by duffn** [comment]
If anybody is still paying attention to this, I have an "Adjustments" column working locally. I'm not sure what the Roll20 character sheet looks like, but in an effort to keep it simpler, I went with the second suggestion.

Does this meet the request?

<img width="715" alt="Screen Shot 2019-12-09 at 5 05 57 PM" src="https://user-images.githubusercontent.com/3457341/70483643-659e7c00-1aa6-11ea-8d3e-43fbb6083754.png">

<img width="709" alt="Screen Shot 2019-12-09 at 5 06 07 PM" src="https://user-images.githubusercontent.com/3457341/70483648-69ca9980-1aa6-11ea-8c85-41f1605f6a5f.png">

cc/ @LtChae @zactru
