### ISSUE TITLE
Consider making Lightsaber and Knowledge: Warfare available to all three systems

### ISSUE THREAD

**Issue by jpactor** [citizenparker/swsheets#95]
Dawn of Rebellion opened those two skills to all three systems, and there are many games with mixed systems involved.

Please consider making those skills available to all game system options.

**Comment by Afinati** [comment]
I was just looking for a way to comment on the same thing. I think, since the books directly reference cross-compatibility, the character creator should endeavor to provide space for Obligations/Morality/Duty and all of the skills in the three games together in one place.

**Comment by sparkertime** [comment]
This sounds like a reasonable request and if any developer would like to add this, I welcome the pull request. However, I'm not adding new features to the site myself these days. I'll leave it here in case someone does.
