### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by infinityfye** [citizenparker/swsheets#96]
I'm terribly sorry if this is the wrong place for this.
I had deleted my browsing history and cookies, so naturally I had to relogin. I got a "No matching username and password could be found", so I clicked the "Forgot your password?" link typed my email, got the email sent flash. But I didn't receive any emails.
I use a password manager to keep all my usernames, emails and passwords. I realise that I may have mistakenly entered some data, but I have tried all 3 of my emails, just to be sure. I didn't receive any emails on any of them.
I'm stuck, any idea on how to proceed?

**Comment by sparkertime** [comment]
Looked into this and unfortunately it looks like Hotmail/Outlook is blocking emails which originate from Mailgun's free-tier IP address. The only general solutions would be to pay for a dedicated IP (which I won't do) or switch providers (which I don't have time to do anytime soon).

I'll personally email you a link this time as a workaround.

**Comment by infinityfye** [comment]
Thank you very much.
