### ISSUE TITLE
Krayt Fang by FakeKenny

### ISSUE THREAD

**Issue by Warhippo** [citizenparker/swsheets#97]
Sorry if this shouldn't posted here but...

Nice job on the Krayt Fang Vehicle Sheet - except that it's got a 'Snuggling Compartment' as a Special Feature. Not sure if that's what FK was really going for :)

**Comment by sparkertime** [comment]
Good eye, but this is only a forum to report bugs or issues on the site itself. I'm not going to edit anyone's sheets and I think it's unlikely the user in question will see this here, so I'm going to politely close this issue.
